# Owns the PostgreSQL container, service exposure, and physical backup/restore hooks.
{ config, lib, postgresPkgs, pkgs, ... }:

let
  cfg = config.portablevps.postgres;
in
{
  options.portablevps.postgres = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the PostgreSQL demo container.";
    };

    dataRoot = lib.mkOption {
      type = lib.types.str;
      default = "/data/postgres";
      description = "Host directory mounted into the PostgreSQL container.";
    };

    dataDir = lib.mkOption {
      type = lib.types.str;
      default = "/data/postgres/18/docker";
      description = "PostgreSQL 18 live cluster directory on the host.";
    };

    backupRoot = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/portablevps-backups/postgres-physical";
      description = "Scratch directory containing the PostgreSQL physical backup chain.";
    };

    containerName = lib.mkOption {
      type = lib.types.str;
      default = "postgres-demo";
      description = "Podman container name.";
    };

    backup.maxChainLength = lib.mkOption {
      type = lib.types.ints.positive;
      default = 24;
      description = ''
        Number of physical backups in a chain before the next backup is
        forced to be a fresh full base backup. Restore replays the whole
        chain with pg_combinebackup, so shorter chains bound both restore
        time and the blast radius of a corrupt chain link. With the hourly
        backup timer the default re-bases once a day.
      '';
    };

    serviceName = lib.mkOption {
      type = lib.types.str;
      default = "postgres.service";
      description = "Systemd service generated by Quadlet.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.etc."containers/systemd/postgres.container".source =
      ./postgres.container;

    systemd.tmpfiles.rules = [
      "d ${cfg.dataRoot} 0755 root root -"
    ];

    portablevps.serviceExposure.services.postgres.netbird.tcp = [
      {
        listenPort = 5432;
        targetHost = "127.0.0.1";
        targetPort = 5432;
        afterServices = [ cfg.serviceName ];
        wantsServices = [ cfg.serviceName ];
      }
    ];

    portablevps.backups.components.postgres = {
      order = 10;
      paths = [ cfg.backupRoot ];
      clearBeforeRestore = [
        cfg.backupRoot
        cfg.dataRoot
      ];
      packages = [
        postgresPkgs.postgresql_18
        pkgs.podman
      ];
      afterServices = [ cfg.serviceName ];
      wantsServices = [ cfg.serviceName ];
      preBackup = ''
        source /run/current-system/sw/bin/runtime-env.sh
        load_postgres_env

        POSTGRES_BACKUP_ROOT="${cfg.backupRoot}"
        POSTGRES_BACKUP_CHAIN_DIR="$POSTGRES_BACKUP_ROOT/chain"
        POSTGRES_BACKUP_METADATA_DIR="$POSTGRES_BACKUP_ROOT/metadata"
        POSTGRES_DATA_DIR="${cfg.dataDir}"

        for _ in $(seq 1 60); do
          if pg_isready -q; then
            break
          fi
          sleep 1
        done

        if ! pg_isready -q; then
          echo "error: PostgreSQL is not ready" >&2
          exit 70
        fi

        replication_hba_line="host replication all all scram-sha-256"
        if [ ! -f "$POSTGRES_DATA_DIR/pg_hba.conf" ]; then
          echo "error: PostgreSQL HBA config not found: $POSTGRES_DATA_DIR/pg_hba.conf" >&2
          exit 70
        fi

        if ! grep -Fxq "$replication_hba_line" "$POSTGRES_DATA_DIR/pg_hba.conf"; then
          printf '\n%s\n' "$replication_hba_line" >>"$POSTGRES_DATA_DIR/pg_hba.conf"
          psql --no-psqlrc --quiet --tuples-only --command='select pg_reload_conf();' >/dev/null
        fi

        mkdir -p "$POSTGRES_BACKUP_CHAIN_DIR" "$POSTGRES_BACKUP_METADATA_DIR"

        backup_id="$(date -u +%Y%m%dT%H%M%SZ)"
        target_dir="$POSTGRES_BACKUP_CHAIN_DIR/$backup_id"
        while [ -e "$target_dir" ]; do
          backup_id="$(date -u +%Y%m%dT%H%M%SZ)-$RANDOM"
          target_dir="$POSTGRES_BACKUP_CHAIN_DIR/$backup_id"
        done

        latest_backup_id=""
        latest_backup_id_path="$POSTGRES_BACKUP_METADATA_DIR/latest-backup-id"
        if [ -r "$latest_backup_id_path" ]; then
          latest_backup_id="$(tr -d '[:space:]' <"$latest_backup_id_path")"
        fi

        chain_length="$(find "$POSTGRES_BACKUP_CHAIN_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d '[:space:]')"

        backup_mode="full"
        incremental_args=()
        if [ -n "$latest_backup_id" ] &&
          [ -r "$POSTGRES_BACKUP_CHAIN_DIR/$latest_backup_id/backup_manifest" ] &&
          [ "$chain_length" -lt ${toString cfg.backup.maxChainLength} ]; then
          backup_mode="incremental"
          incremental_args=(
            "--incremental=$POSTGRES_BACKUP_CHAIN_DIR/$latest_backup_id/backup_manifest"
          )
        fi

        pg_basebackup \
          --pgdata="$target_dir" \
          --format=plain \
          --wal-method=stream \
          --checkpoint=fast \
          "''${incremental_args[@]}"

        pg_verifybackup "$target_dir"

        if [ "$backup_mode" = "full" ]; then
          # A verified full starts a new chain. Drop older chain entries and
          # stale metadata so the scratch directory and the restic snapshot
          # hold exactly one chain; older chains stay in older snapshots.
          find "$POSTGRES_BACKUP_CHAIN_DIR" -mindepth 1 -maxdepth 1 -type d \
            ! -name "$backup_id" -exec rm -rf {} +
          find "$POSTGRES_BACKUP_METADATA_DIR" -mindepth 1 -maxdepth 1 \
            -name '*.mode' ! -name "$backup_id.mode" -delete
        fi

        printf '%s\n' "$backup_id" >"$latest_backup_id_path"
        printf '%s\n' "$backup_mode" >"$POSTGRES_BACKUP_METADATA_DIR/$backup_id.mode"

        echo "postgres backup mode: $backup_mode"
        echo "postgres backup id: $backup_id"
      '';
      preRestore = ''
        if podman container exists ${cfg.containerName} >/dev/null 2>&1 &&
          [ "$(podman inspect -f '{{.State.Running}}' ${cfg.containerName})" = "true" ]; then
          echo "error: refusing restore while ${cfg.containerName} container is running" >&2
          exit 78
        fi
      '';
      postRestore = ''
        POSTGRES_BACKUP_ROOT="${cfg.backupRoot}"
        POSTGRES_BACKUP_CHAIN_DIR="$POSTGRES_BACKUP_ROOT/chain"
        POSTGRES_DATA_DIR="${cfg.dataDir}"

        if [ ! -d "$POSTGRES_BACKUP_CHAIN_DIR" ]; then
          echo "error: restore did not create $POSTGRES_BACKUP_CHAIN_DIR" >&2
          exit 70
        fi

        mapfile -t backup_dirs < <(
          find "$POSTGRES_BACKUP_CHAIN_DIR" -mindepth 1 -maxdepth 1 -type d | sort
        )

        if [ "''${#backup_dirs[@]}" -eq 0 ]; then
          echo "error: no PostgreSQL physical backups found in $POSTGRES_BACKUP_CHAIN_DIR" >&2
          exit 70
        fi

        work_dir="$(mktemp -d /tmp/portablevps-pg-combine.XXXXXX)"
        combined_dir="$work_dir/combined"
        cleanup() {
          rm -rf "$work_dir"
        }
        trap cleanup EXIT

        pg_combinebackup --output="$combined_dir" "''${backup_dirs[@]}"

        mkdir -p ${cfg.dataRoot}
        find ${cfg.dataRoot} -mindepth 1 -maxdepth 1 -exec rm -rf {} +
        mkdir -p "$POSTGRES_DATA_DIR"
        tar -C "$combined_dir" -cf - . | tar -C "$POSTGRES_DATA_DIR" -xf -
      '';
    };
  };
}
